version: '3'
services:
  prisma_prorail:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "5566:5566"
    environment:
      PRISMA_CONFIG: |
        port: 5566
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: db_prorail
            database: default@prorail
            user: root
            password: root
            rawAccess: true
            port: 3306
            migrations: true
  db_prorail:
    image: mysql:5.7
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
    ports:
    - "3306:3306" 
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
